package app

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"

	"github.com/dotcommander/gokart/cache"

	"github.com/spf13/viper"
)

// Config key constants — single source of truth between viper defaults and readers.
const (
	AppConfigKeyRedisAddr = "redis_addr"
)

// Dependencies holds shared application dependencies.
type Dependencies struct {
	Log   *slog.Logger
	Cache *cache.Cache
}

// Context is retained for commands generated by earlier GoKart releases.
type Context = Dependencies

// New creates application dependencies with config from viper.
func New(ctx context.Context, appName string, v *viper.Viper) (_ *Dependencies, err error) {
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	appCtx := &Dependencies{
		Log: logger,
	}
	defer func() {
		if err == nil {
			return
		}
		if cleanupErr := appCtx.Close(); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("close partially initialized dependencies: %w", cleanupErr))
		}
	}()

	// Setup Redis cache
	redisAddr := v.GetString(AppConfigKeyRedisAddr)
	if redisAddr == "" {
		redisAddr = os.Getenv("REDIS_ADDR")
	}
	if redisAddr == "" {
		redisAddr = "localhost:6379"
	}
	cacheClient, err := cache.Open(ctx, redisAddr)
	if err != nil {
		return nil, fmt.Errorf("open cache: %w", err)
	}
	appCtx.Cache = cacheClient

	return appCtx, nil
}

// Close releases resources.
func (c *Dependencies) Close() error {
	var cleanupErrors []error
	if c.Cache != nil {
		cleanupErrors = append(cleanupErrors, c.Cache.Close())
	}
	return errors.Join(cleanupErrors...)
}
