package app

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"

	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"

	"github.com/spf13/viper"
)

// Config key constants — single source of truth between viper defaults and readers.
const (
	AppConfigKeyOpenAIAPIKey = "openai_api_key"
)

// Dependencies holds shared application dependencies.
type Dependencies struct {
	Log *slog.Logger
	AI  openai.Client
}

// Context is retained for commands generated by earlier GoKart releases.
type Context = Dependencies

// New creates application dependencies with config from viper.
func New(ctx context.Context, appName string, v *viper.Viper) (_ *Dependencies, err error) {
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	appCtx := &Dependencies{
		Log: logger,
	}
	defer func() {
		if err == nil {
			return
		}
		if cleanupErr := appCtx.Close(); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("close partially initialized dependencies: %w", cleanupErr))
		}
	}()

	// Setup OpenAI client
	apiKey := v.GetString(AppConfigKeyOpenAIAPIKey)
	if apiKey == "" {
		apiKey = os.Getenv("OPENAI_API_KEY")
	}
	if apiKey == "" {
		logger.Warn("OPENAI_API_KEY not set, AI features will not work")
	}
	appCtx.AI = openai.NewClient(option.WithAPIKey(apiKey))

	return appCtx, nil
}

// Close releases resources.
func (c *Dependencies) Close() error {
	var cleanupErrors []error
	return errors.Join(cleanupErrors...)
}
