package app

import (
	"context"
	"errors"
	"fmt"
	"github.com/dotcommander/gokart/postgres"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	"os"

	"github.com/spf13/viper"
)

// Config key constants — single source of truth between viper defaults and readers.
const (
	AppConfigKeyDatabaseURL = "database_url"
)

// Dependencies holds shared application dependencies.
type Dependencies struct {
	Log  *slog.Logger
	Pool *pgxpool.Pool
}

// Context is retained for commands generated by earlier GoKart releases.
type Context = Dependencies

// New creates application dependencies with config from viper.
func New(ctx context.Context, appName string, v *viper.Viper) (_ *Dependencies, err error) {
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	appCtx := &Dependencies{
		Log: logger,
	}
	defer func() {
		if err == nil {
			return
		}
		if cleanupErr := appCtx.Close(); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("close partially initialized dependencies: %w", cleanupErr))
		}
	}()

	// Setup PostgreSQL connection pool
	dbURL := v.GetString(AppConfigKeyDatabaseURL)
	if dbURL == "" {
		dbURL = os.Getenv("DATABASE_URL")
	}
	if dbURL == "" {
		logger.Warn("DATABASE_URL not set, PostgreSQL features will not work")
	} else {
		pool, err := postgres.Open(ctx, dbURL)
		if err != nil {
			return nil, fmt.Errorf("connect to postgres: %w", err)
		}
		appCtx.Pool = pool
	}

	return appCtx, nil
}

// Close releases resources.
func (c *Dependencies) Close() error {
	var cleanupErrors []error
	if c.Pool != nil {
		c.Pool.Close()
	}
	return errors.Join(cleanupErrors...)
}
