package app

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/dotcommander/gokart/sqlite"

	"github.com/spf13/viper"
)

// Config key constants — single source of truth between viper defaults and readers.
const (
	AppConfigKeyDBPath = "db_path"
)

// Dependencies holds shared application dependencies.
type Dependencies struct {
	Log *slog.Logger
	DB  *sql.DB
}

// Context is retained for commands generated by earlier GoKart releases.
type Context = Dependencies

// New creates application dependencies with config from viper.
func New(ctx context.Context, appName string, v *viper.Viper) (_ *Dependencies, err error) {
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	appCtx := &Dependencies{
		Log: logger,
	}
	defer func() {
		if err == nil {
			return
		}
		if cleanupErr := appCtx.Close(); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("close partially initialized dependencies: %w", cleanupErr))
		}
	}()

	// Setup SQLite database
	dbPath := v.GetString(AppConfigKeyDBPath)
	if dbPath == "" {
		cacheDir, err := os.UserCacheDir()
		if err != nil {
			return nil, err
		}
		dbDir := filepath.Join(cacheDir, appName)
		if err := os.MkdirAll(dbDir, 0755); err != nil {
			return nil, err
		}
		dbPath = filepath.Join(dbDir, "data.db")
	}

	db, err := sqlite.Open(dbPath)
	if err != nil {
		return nil, err
	}
	appCtx.DB = db

	return appCtx, nil
}

// Close releases resources.
func (c *Dependencies) Close() error {
	var cleanupErrors []error
	if c.DB != nil {
		cleanupErrors = append(cleanupErrors, c.DB.Close())
	}
	return errors.Join(cleanupErrors...)
}
